#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/app/scrutiny.yaml" ]]; then
    echo "Installing default \"scrutiny.yaml\"..."
    cp "${APP_DIR}/scrutiny.yaml" "${CONFIG_DIR}/app/scrutiny.yaml"
    chown hotio:hotio "${CONFIG_DIR}/app/scrutiny.yaml"
fi

if [[ "${MODE}" == web ]]; then
    rm -rf /etc/services.d/collector
fi

if [[ "${MODE}" == collector ]]; then
    rm -rf /etc/services.d/web
fi
